"""add_checked_field

Revision ID: 8b5e6e6117e9
Revises: 3679e03f5287
Create Date: 2025-02-03 14:27:29.265065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b5e6e6117e9'
down_revision: Union[str, None] = '3679e03f5287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'checked')
    # ### end Alembic commands ###
